<?php
defined('ABSPATH') || exit;
// Update only the exact sentence generated by version 1.0; preserve all other page edits.
add_action('admin_init', function () {
    if (!current_user_can('manage_options') || get_option('bilyan_copy_version') === '1.1') return;
    $page = get_page_by_path('terms');
    if ($page) {
        $old = 'Products marked “' . 'Ask' . ' for a quote” will be quoted by our team.';
        $new = 'For products without a listed price, our team will confirm pricing after submission.';
        if (str_contains($page->post_content, $old)) {
            $result = wp_update_post(wp_slash(['ID' => $page->ID, 'post_content' => str_replace($old, $new, $page->post_content)]), true);
            if (is_wp_error($result)) return;
        }
    }
    update_option('bilyan_copy_version', '1.1', false);
});
add_action('after_switch_theme', function () {
    bilyan_register_types();
    $pages = [
        'cart' => ['Your cart', ''],
        'about' => ['About Bilyan', ''],
        'contact' => ['Contact us', ''],
        'faq' => ['Frequently asked questions', ''],
        'privacy' => ['Privacy policy', '<h2>Your information</h2><p>When you submit an order request, Bilyan collects your name, email, phone number, delivery address, selected products and any notes you provide. We use these details to respond to your request and arrange your order.</p><h2>Storage and sharing</h2><p>Order details are stored on this website and sent to our order notification email address. Our website hosting and email providers process this information to operate these services. We do not collect online payment details.</p><h2>Your browser</h2><p>Your cart is saved in local storage on your device so it remains available when you return. Removing all products clears the cart contents. Standard WordPress cookies may be used for signed-in users.</p><h2>Your choices</h2><p>To ask about your information, request a correction or request deletion of an order record, email hellobilyan@gmail.com. Please do not include sensitive personal information in order notes.</p>'],
        'terms' => ['Ordering & delivery', '<h2>Order requests</h2><p>Submitting your cart sends an order request to Bilyan. It does not collect payment or guarantee stock. Our team will contact you to confirm product availability, final prices and delivery arrangements.</p><h2>Prices and delivery</h2><p>Displayed prices are estimates for the listed products. For products without a listed price, our team will confirm pricing after submission. Delivery charges and any applicable taxes are confirmed before you agree to an order.</p><h2>Changes and returns</h2><p>To change or cancel a request, contact us with your order reference. Ask our team about the return terms for your specific products before confirming your order. Nothing on this page limits applicable consumer rights.</p>'],
    ];
    foreach ($pages as $slug => $page) {
        if (!get_page_by_path($slug)) wp_insert_post(['post_type' => 'page', 'post_status' => 'publish', 'post_name' => $slug, 'post_title' => $page[0], 'post_content' => $page[1]]);
    }
    bilyan_seed_faqs();
    flush_rewrite_rules();
});
add_action('admin_init', function () {
    if (current_user_can('manage_options')) bilyan_seed_faqs();
});
add_action('init', function () {
    if (!get_option('bilyan_faq_seeded')) {
        bilyan_seed_faqs();
        update_option('bilyan_faq_seeded', '1', false);
    }
}, 20);
function bilyan_seed_faqs() {
    if (get_posts(['post_type' => 'bilyan_faq', 'post_status' => 'publish', 'numberposts' => 1])) return;
    $faqs = [
        ['How do I place an order?', 'Browse our products, add your favorites to the cart and choose your quantities. In your cart, fill in your contact details and delivery address, then select “Send order request”. Save the reference shown after submission.'],
        ['Do I need to pay online?', 'No. This website does not collect payments. After receiving your request, our team will contact you to confirm availability, final prices, delivery and any payment arrangements.'],
        ['Can I order a product without a listed price?', 'Some products do not have a listed price. You can still add them to your cart and send your order request. Our team will confirm pricing before you agree to the order.'],
        ['Where do you deliver?', 'We are based in Mogadishu, Somalia. Include your delivery area with your request. Our team will confirm whether delivery is available to your address and any delivery charge before you confirm your order.'],
        ['Can I change or cancel my request?', 'Yes, contact us as soon as possible with your order reference and the changes you need. Our team will confirm what can be arranged.'],
        ['How do I know my request was received?', 'A confirmation screen with a BLY reference appears when your request has been saved. Keep that reference. If you see an error instead, follow the message and try again.'],
        ['Do I need an account?', 'No account is required. Your cart is saved in this browser, and you provide your contact details when sending an order request.'],
    ];
    foreach ($faqs as $order => $faq) wp_insert_post(['post_type' => 'bilyan_faq', 'post_status' => 'publish', 'post_title' => $faq[0], 'post_content' => $faq[1], 'menu_order' => $order]);
}
add_action('admin_menu', function () { add_theme_page('Bilyan setup', 'Bilyan setup', 'manage_options', 'bilyan-setup', 'bilyan_setup_screen'); });
add_action('admin_init', function () {
    register_setting('bilyan', 'bilyan_settings', ['sanitize_callback' => function ($input) {
        return ['email' => sanitize_email($input['email'] ?? ''), 'address' => sanitize_text_field($input['address'] ?? ''), 'currency' => substr(strtoupper(sanitize_text_field($input['currency'] ?? 'USD')), 0, 8)];
    }]);
});
function bilyan_setup_screen() {
    if (!current_user_can('manage_options')) return;
    ?>
    <div class="wrap"><h1>Bilyan setup</h1><p>Your all-in-one marketplace. No payment gateway or WooCommerce required.</p>
    <form method="post" action="options.php"><?php settings_fields('bilyan'); ?>
    <table class="form-table"><tr><th><label for="bilyan-email">Order notification email</label></th><td><input class="regular-text" id="bilyan-email" type="email" required name="bilyan_settings[email]" value="<?php echo esc_attr(bilyan_email()); ?>"></td></tr>
    <tr><th><label for="bilyan-address">Business address</label></th><td><input class="regular-text" id="bilyan-address" name="bilyan_settings[address]" value="<?php echo esc_attr(bilyan_address()); ?>"></td></tr>
    <tr><th><label for="bilyan-currency">Currency label</label></th><td><input id="bilyan-currency" name="bilyan_settings[currency]" maxlength="8" value="<?php echo esc_attr(bilyan_setting('currency', 'USD')); ?>"><p class="description">Defaults to USD. No conversion is performed. Update product prices when changing currency.</p></td></tr></table>
    <?php submit_button(); ?></form>
    <hr><h2>品牌与静态内容</h2><p>Logo、站点图标：首页、About、联系页、页脚及主题配色可在自定义面板管理。About 完整正文也可切换到页面编辑器。</p><p><a class="button button-primary" href="<?php echo esc_url(admin_url('customize.php')); ?>">打开外观自定义</a></p><h2>Getting started</h2><ol><li>Add categories under <strong>Products → Product categories</strong>.</li><li>Add products with title, excerpt, description and featured image. Price is optional.</li><li>Review requests under <strong>Orders</strong> and update their status.</li><li>Configure an SMTP mail plugin and send a test email before launch.</li><li>Review the Privacy policy and Ordering & delivery pages for your actual business policies.</li></ol>
    <h2>Optional sample catalog</h2><p>Add six clearly labeled demonstration products with bundled illustrations. These are examples, not actual inventory. Remove them or replace their details and images before launch. Importing twice will not duplicate them.</p>
    <form action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post"><input type="hidden" name="action" value="bilyan_demo"><?php wp_nonce_field('bilyan_demo'); submit_button('Import sample products', 'secondary'); ?></form></div>
    <?php
}
add_action('admin_post_bilyan_demo', function () {
    if (!current_user_can('manage_options')) wp_die('Not permitted.');
    check_admin_referer('bilyan_demo');
    bilyan_import_demo();
    wp_safe_redirect(admin_url('edit.php?post_type=bilyan_product')); exit;
});
function bilyan_import_demo() {
    $samples = [
        ['Wireless headphones', 'Electronics', 'headphones', '49.00', 'A little more music. A little less noise. Comfortable headphones for everyday listening.'],
        ['Everyday canvas tote', 'Fashion & accessories', 'bag', '18.00', 'Room for the essentials, wherever your day takes you.'],
        ['Modern accent chair', 'Home & living', 'chair', '125.00', 'A comfortable corner starts here. A simple silhouette for your home.'],
        ['Minimal desk lamp', 'Home & living', 'lamp', '32.00', 'A warm finishing touch for your desk or bedside.'],
        ['Classic everyday watch', 'Fashion & accessories', 'watch', '39.00', 'Clean details and timeless style for every day.'],
        ['Reusable water bottle', 'Sports & outdoors', 'bottle', '15.00', 'Your everyday companion for work, walks and everything between.'],
    ];
    foreach ($samples as $index => $sample) {
        $slug = 'sample-' . $sample[2];
        if (get_page_by_path($slug, OBJECT, 'bilyan_product')) continue;
        $term = term_exists($sample[1], 'bilyan_category');
        if (!$term) $term = wp_insert_term($sample[1], 'bilyan_category');
        $id = wp_insert_post(['post_type' => 'bilyan_product', 'post_status' => 'publish', 'post_title' => $sample[0], 'post_name' => $slug, 'post_excerpt' => $sample[4], 'post_content' => '<p>' . $sample[4] . '</p><p><strong>Demonstration product.</strong> This sample shows how a Bilyan product page looks. Replace the description, price and illustration with your actual product information before accepting orders.</p>'], true);
        if (is_wp_error($id)) continue;
        if (!is_wp_error($term)) wp_set_object_terms($id, (int) (is_array($term) ? $term['term_id'] : $term), 'bilyan_category');
        update_post_meta($id, '_bilyan_price', $sample[3]);
        update_post_meta($id, '_bilyan_demo_image', $sample[2]);
        update_post_meta($id, '_bilyan_sku', 'DEMO-00' . ($index + 1));
        update_post_meta($id, '_bilyan_featured', '1');
    }
}
