<?php defined('ABSPATH') || exit; get_header(); ?>
<?php if (bilyan_content('show_hero')): ?><section class="hero container"><div class="hero-copy"><span class="eyebrow"><span class="red-dot"></span> <?php echo esc_html(bilyan_content('hero_eyebrow')); ?></span><h1><?php echo esc_html(bilyan_content('hero_title')); ?><br><em><?php echo esc_html(bilyan_content('hero_accent')); ?></em></h1><p><?php echo nl2br(esc_html(bilyan_content('hero_description'))); ?></p><a class="button" href="<?php echo esc_url(bilyan_content('hero_url') ?: get_post_type_archive_link('bilyan_product')); ?>"><?php echo esc_html(bilyan_content('hero_button')); ?> <?php echo bilyan_icon('arrow'); ?></a><div class="hero-caption"><span class="small-check"><?php echo bilyan_icon('check'); ?></span> <?php echo esc_html(bilyan_content('hero_caption')); ?></div></div><div class="hero-art"><span class="hero-circle"></span><span class="hero-art-label"><?php echo nl2br(esc_html(bilyan_content('hero_art_label'))); ?></span><img class="hero-headphones" src="<?php echo esc_url(bilyan_content_image('hero_image', get_template_directory_uri() . '/assets/images/headphones.svg')); ?>" alt="<?php echo esc_attr(bilyan_content('hero_image') ? get_post_meta(bilyan_content('hero_image'), '_wp_attachment_image_alt', true) : 'Illustration of cream wireless headphones'); ?>" width="600" height="600"><div class="hero-tag"><span class="tag-icon"><?php echo bilyan_icon('heart'); ?></span><span><?php echo esc_html(bilyan_content('hero_tag')); ?><strong><?php echo esc_html(bilyan_content('hero_tag_strong')); ?></strong></span></div><span class="hero-star" aria-hidden="true">✳</span></div></section><?php endif; ?>
<?php if (bilyan_content('show_benefits')): ?><section class="container benefits" aria-label="Shopping at Bilyan"><div><?php echo bilyan_icon('box'); ?><span><strong><?php echo esc_html(bilyan_content('benefit_1_title')); ?></strong><small><?php echo esc_html(bilyan_content('benefit_1_body')); ?></small></span></div><div><?php echo bilyan_icon('cart'); ?><span><strong><?php echo esc_html(bilyan_content('benefit_2_title')); ?></strong><small><?php echo esc_html(bilyan_content('benefit_2_body')); ?></small></span></div><div><?php echo bilyan_icon('headphones'); ?><span><strong><?php echo esc_html(bilyan_content('benefit_3_title')); ?></strong><small><?php echo esc_html(bilyan_content('benefit_3_body')); ?></small></span></div><div><?php echo bilyan_icon('pin'); ?><span><strong><?php echo esc_html(bilyan_content('benefit_4_title')); ?></strong><small><?php echo esc_html(bilyan_content('benefit_4_body')); ?></small></span></div></section><?php endif; ?>
<?php if (bilyan_content('show_categories')): ?><section class="container section front-page-categories"><div class="section-heading"><div><span class="eyebrow"><?php echo esc_html(bilyan_content('categories_eyebrow')); ?></span><h2><?php echo esc_html(bilyan_content('categories_title')); ?></h2></div><a class="text-link" href="<?php echo esc_url(get_post_type_archive_link('bilyan_product')); ?>"><?php echo esc_html(bilyan_content('categories_button')); ?> <?php echo bilyan_icon('arrow'); ?></a></div><div class="categories">
<?php $categories = get_terms(['taxonomy' => 'bilyan_category', 'hide_empty' => false, 'number' => 6]);
if (!is_wp_error($categories) && $categories) { foreach ($categories as $category) {
    echo '<a class="category-card" href="' . esc_url(get_term_link($category)) . '"><span class="category-image"><img loading="lazy" src="' . esc_url(bilyan_category_image($category)) . '" alt="' . esc_attr($category->name) . '"></span><span class="category-card-copy"><strong>' . esc_html($category->name) . '</strong><small>' . esc_html($category->count) . ' products</small></span><span class="category-card-arrow">' . bilyan_icon('arrow') . '</span></a>';
} } else { foreach (['Electronics' => 'headphones', 'Fashion & accessories' => 'bag', 'Home & living' => 'chair', 'Beauty & care' => 'lamp', 'Sports & outdoors' => 'bottle', 'More to discover' => 'placeholder'] as $label => $image) echo '<a class="category-card" href="' . esc_url(get_post_type_archive_link('bilyan_product')) . '"><span class="category-image"><img loading="lazy" src="' . esc_url(get_template_directory_uri() . '/assets/images/' . $image . '.svg') . '" alt="' . esc_attr($label) . '"></span><span class="category-card-copy"><strong>' . esc_html($label) . '</strong><small>Explore our catalog</small></span><span class="category-card-arrow">' . bilyan_icon('arrow') . '</span></a>'; } ?>
</div></section><?php endif; ?>
<?php if (bilyan_content('show_featured')): ?><section class="container section"><div class="section-heading"><div><span class="eyebrow"><?php echo esc_html(bilyan_content('featured_eyebrow')); ?></span><h2><?php echo esc_html(bilyan_content('featured_title')); ?></h2></div><a class="text-link" href="<?php echo esc_url(get_post_type_archive_link('bilyan_product')); ?>"><?php echo esc_html(bilyan_content('featured_button')); ?> <?php echo bilyan_icon('arrow'); ?></a></div><div class="product-grid">
<?php $products = new WP_Query(['post_type' => 'bilyan_product', 'posts_per_page' => bilyan_content('featured_count'), 'meta_key' => '_bilyan_featured', 'meta_value' => '1', 'has_password' => false]);
if (!$products->have_posts()) $products = new WP_Query(['post_type' => 'bilyan_product', 'posts_per_page' => bilyan_content('featured_count'), 'has_password' => false]);
if ($products->have_posts()) { while ($products->have_posts()) { $products->the_post(); bilyan_product_card(get_the_ID()); } } else { ?><div class="empty-state"><h3>Good things are on their way.</h3><p>Our collection is coming together. Contact us to ask about a product.</p><a class="text-link" href="<?php echo esc_url(bilyan_page_url('contact')); ?>">Get in touch →</a></div><?php } wp_reset_postdata(); ?></div></section><?php endif; ?>
<?php if (bilyan_content('show_story')): ?><section class="container story-banner"><div><span class="eyebrow"><?php echo esc_html(bilyan_content('story_eyebrow')); ?></span><h2><?php echo nl2br(esc_html(bilyan_content('story_title'))); ?></h2><p><?php echo esc_html(bilyan_description()); ?></p><a class="button button-white" href="<?php echo esc_url(bilyan_content('story_url') ?: bilyan_page_url('about')); ?>"><?php echo esc_html(bilyan_content('story_button')); ?> <?php echo bilyan_icon('arrow'); ?></a></div><?php if (bilyan_content_image('story_image')): ?><div class="story-image"><?php echo wp_get_attachment_image(bilyan_content('story_image'), 'large'); ?></div><?php else: ?><div class="story-graphic" aria-hidden="true"><span>All</span><span>In One</span><span>Place<span class="graphic-dot">.</span></span></div><?php endif; ?></section><?php endif; ?>
<?php if (bilyan_content('show_steps')): ?><section class="container section how-it-works"><div class="section-heading"><div><span class="eyebrow"><?php echo esc_html(bilyan_content('steps_eyebrow')); ?></span><h2><?php echo esc_html(bilyan_content('steps_title')); ?></h2></div><p><?php echo esc_html(bilyan_content('steps_note')); ?></p></div><div class="steps"><div><span>01</span><h3><?php echo esc_html(bilyan_content('step_1_title')); ?></h3><p><?php echo esc_html(bilyan_content('step_1_body')); ?></p></div><div><span>02</span><h3><?php echo esc_html(bilyan_content('step_2_title')); ?></h3><p><?php echo esc_html(bilyan_content('step_2_body')); ?></p></div><div><span>03</span><h3><?php echo esc_html(bilyan_content('step_3_title')); ?></h3><p><?php echo esc_html(bilyan_content('step_3_body')); ?></p></div></div></section><?php endif; ?>
<?php get_footer(); ?>
